import random
kelimeler = ["gözəl ","məlumat ","sual","sağlam ","Buraxmaq","Vaxt","su","etmək","istifadə etmək","yox","görmək",
             "dərinizdən", "çox", "Amma", "lirə", "oynamaq", "çiçək", "şəhər", "yüksəlmək", "mübarizə", "Mövcudluq", "Etmək",
             "güvən", "Zəruri", "Müalicə", "Vahid", "rahat", "soyuq", "orada", "kitab", "paylaşmaq", "hesab", "bədən",
             "Torpaq", "bitdi", "sistem", "xoş", "çəkilmək", "tekniki", "yanaşma", "il", "tarix", "Mütləq", "bacı",
             "Nazik", "əgər", "Halbuki", "əks","vermək", "sahib", "artıq", "kişi", "digər", "dövr", "Hələ", "bunlar",
             "kitab", "Hadisə", "var", "siz", "dövlət", "ön", "en", "baxmaq", "bitdi", "kimi", "Bəziləri", "başlamaq",
             "tutmaq", "birbirinə", "Yox", "Etmək", "su", "kimi", "hal", "doğru", "orta", "başqa", "böyük", "etmək",
             "yeni", "Daha çox", "Soruşmaq", "onlar", "açıq", "hər ikisi", "həmişə", "səs", "anlamaq", "yox", "saat", "Necə",
             'bir', 'və', 'olmaq', 'bu', 'üçün', 'o', 'mən', 'Deməli', 'çox', 'Etmək', 'nə', 'kimi', 'daha', 'almaq',
             'var', 'Öz', 'Gəlmək', 'ilə', 'vermək', 'amma', 'sonra', 'qədər', 'yer', 'en', 'insan', 'deyil', 'hər',
             'istəmək', 'il', 'çıxmaq', 'görmək', 'gün', 'biz', 'Getmək', 'iş', 'şey', 'Axtar', 'ki', 'bilmək', 'əl', 'Vaxt',
             'ya', 'uşaq', 'iki', 'baxmaq', 'çalışmaq', 'içəri', 'böyük', 'yox', 'başlamaq', 'yol', 'Qalxmaq', 'Niyə?', 'siz',
             'Mövzu', 'Bitsin', 'Yaxşı', 'qadın', 'ev', 'deyərək', 'var', 'Demək', 'göz', 'ehtiyac', 'dünya',
             'baş', 'Vəziyyət', 'yan', 'getmək', 'sən', 'onlar', 'yeni', 'Əvvəl', 'başqa', 'hal', 'orta', 'su', 'daxil olmaq', 'ölkə',
             'yemək', 'heç', 'Hətta', 'Necə', 'bütün', 'qarşı', 'tapmaq', 'bunun kimi', 'yaşamaq', 'düşünmək', 'eyni', 'daxili', 'ancaq',
             'kişi', 'bunlar', 'vəya', 'ilk', 'tərəfindən', 'ön', 'son', 'kimsə', 'şəkil', 'Əhəmiyyətli', 'üz', 'həm', 'göstərmək', 'etmək',
             'alt', 'getirmək', 'istifadə etmək', 'çünki', 'tərəf', 'İndi', 'adam', 'onun', 'Digər', 'artıq', 'haqqında', 'səs', 'həmişə',
             'doğru', 'durmak', 'kız', 'tüm', 'çekmek', 'konuşmak', 'para', 'anlamak', 'anne', 'az', 'bazı', 'baba', 'hayat',
             'sadəcə', 'kiçik', 'Daha çox', 'məlumat', 'an', 'soruşmaq', 'bu', 'belə', 'hələ', 'təmin etmək', 'nəticə', 'istifadə etmək', 'xarici',
             'ad', 'yaxşı', 'müddəti', 'qayıtmaq', 'açmaq', 'oturmaq', 'anlatmaq', 'Tərk etmək', 'İndi', 'saat', 'yaş', 'problem', 'dövlət',
             'sahip', 'sıra', 'yazmak', 'yüzde', 'ay', 'atmak', 'tutmak', 'bunu', 'olay', 'düşmek', 'duymak', 'söz', 'güzel',
             'sevmək', 'biraz', 'zor', 'çıxmaq', 'bu', 'qoymaq', 'tək', 'sistem', 'birlikdə', 'verilmək', 'kim', 'alınmaq', 'gənc',
             'qapı', 'kitab', 'bitdi', 'burada', 'gecə', 'sahə', 'birbirinə', 'Sorğu', 'gözləmək', 'uzun', 'yox', 'bugün', 'dövr',
             'dost', 'məhsul', 'ailə', 'üç', 'oxumaq', 'kişi', 'hərkəs', 'güc', 'belkə', 'real', 'tam', 'bağlı', 'münasibət',
             'çevrə', 'köhnə', 'Axtarış', 'həyat', 'Xalq', 'yaxın', 'Küçə', 'bəy', 'tarix', 'xüsusiyyət', 'bölüm', 'xüsusi', 'ağıl',
             'heçkim', 'çox', 'əgər', 'zəruri', 'xüsusilə', 'məna', 'yüksək', 'bank', 'dəfə', 'ayaq', 'daşımaq', 'geri', 'cəmiyyət',
             'Maşın', 'Məsələ', 'növü', 'qərar', 'görülmək', 'hava', 'nömrə', 'fərqli', 'grup', 'otaq', 'format', 'olmaq', 'xəbərlər',
             'allah', 'Üstəlik', 'gələn', 'biraz', 'sual', 'arxa', 'Qazanmaq', 'yazı', 'məktəb', 'açıq', 'öyrənmək', 'yayılmaq',
             'dil', 'şirkət', 'mənbə', 'bitmək', 'proqram', 'davametmək', 'hərəkat', 'rəng', 'açılmaq', 'sağ', 'inanmaq',
             'Öyrənmək', 'Ağrı', 'parça', 'qəzet', 'oluşturmaq', 'tabedir', 'Dəyər', 'tanımaq', 'strukturu', 'həkim', 'gəlir',
             'vəzifə', 'məqsəd', 'bölgə', 'film', 'haqqında', 'müştəri', 'artıq', 'telefon', 'təhsil', 'dəniz', 'ikinci',
             'qalmaq', 'hətta', 'təsiri', 'inkişafetmək', 'sonuncu', 'bədən', 'fikir', 'milyon', 'oynamaq', 'dəyişən', 'əsas',
             'yaratmaq', 'Çatmaq', 'fikirləşmək', 'qoymaq', 'mədəniyyət', 'yaratmaq', 'Amma', 'bu', 'rəsim', 'işıq', 'içmək',
             'xanım', 'xidmət', 'ehtiyac', 'nöqtə', 'istiqamət', 'Bəli', 'oyun', 'artmaq', 'yenidən', 'proses', 'qısa', 'asan',
             'hansı', 'nisbət', 'əslində', 'qəbuletmək', 'orada', 'diqqət', 'uzaq', 'Kompüter', 'gələcək', 'görünmək',
             'məs', 'oğul', 'Qulaqasmaq', 'uyğun', 'lirə', 'istehsal', 'dəqiqə', 'unutmaq', 'gəzmək', 'beləliklə', 'pis',
             'maşın', 'ağız', 'hiss', 'tətbiqetmək', 'hələ', 'nümunə', 'çoxlu', 'baxmaq', 'dərəcə', 'mümkün', 'bununkimi',
             'divar', 'on', 'incəsənət', 'ana', 'xəstəlik', 'tələbə', 'televizor', 'üsul', 'masa', 'ölmək', 'Komanda', 'üst',
             'baş', 'musiqi', 'ayrılmaq', 'enerji', 'universitet', 'İdman', 'növləri', 'can', 'rəğmən', 'hissəsi', 'ölüm',
             'davamlıolaraq', 'sağlamlıq', 'müxtəlif', 'bundan', 'hissetmək', 'Halbuki', 'sabah', 'internet', 'tekniki', 'cöl',
             'mərkəz', 'mühit', 'yerinə', 'səviyyə', 'Kənd', 'İdarəetmə', 'aşağı', 'cavab', 'yatmaq', 'torpaq', '', 'axşam',
             'Araşdırma', 'götürmək', 'qatılmaq', 'yoxsa', 'Qurulmaq', 'ödəmək', 'sakin', 'qan', 'xəstə', 'şəhər', 'enmək',
             'Təqdim', 'tanınmaq', 'həftə', 'Tıxac', 'hesab', 'avtomobil', 'xarici', 'davranış', 'mətbəx', 'Şəhərcik', 'bəzən',
             'bəlli', 'ayrı', 'qiymət', 'haqqında', 'qaldırmaq', 'qol', 'tək', 'hazırlamaq', 'şam', 'nəhayət', 'yavaş',
             'zəruri', 'önəmli', 'qoca', 'yanlış', 'varlıq', 'art', 'maraq', 'sənə', 'satış', 'içəri', 'təbii', 'sahibolmak',
             'Ekonomiya', 'acı', 'Yox', 'Qorumaq', 'mərtəbə', 'ekonomi', 'general', 'göstərmək', 'fotoşəkil', 'heyvan', 'müharibə',
             'mal', 'saç', 'itirmək', 'qalıq', 'dəyişmək', 'dörd', 'həqiqətən', 'səhifə', 'texnoloji', 'qurum', 'beş',
             'sektor', 'geniş', 'kağız', 'qoxu', 'sağ', 'isti', 'yüzil', 'Küçə', 'bazar', 'davametmək', 'istifadəedin', 'sinif',
             'sevgi', 'doğmaq', 'ağır', 'təkrar', 'günəş', 'siqaret', 'ağaç', 'söz', 'bina', 'həyatyoldaşı', 'qaçmaq', 'partiya', 'yataq',
             'müəllif', 'qulaq', 'müəllim', 'səbəb', 'sol', 'yaxşı', 'yağ', 'niyə', 'anlaşılmaq', 'gəlmək', 'gülmək', 'qayda',
             'satmaq', 'şeir', 'göndərmək', 'uğur', 'firma', 'hökumət', 'ürək', 'kəsmək', 'layihə', 'lazımdır', 'sürət', 'künc',
             'vurmaq', 'model', 'balıq', 'bazar', 'görüş', 'bura', 'hazırlanmaq', 'kəmiyyət', 'birinci', 'meydan', 'ölçü',
             'seçmək', 'uygulanmaq', 'bağ', 'sevgi', 'çörək', 'boyunca', 'qaçmaq', 'dolu', 'müəssisə', 'təşəkkürlər', 'qorxmaq',
             'kömək', 'qarşılaşmaq', 'material', 'xoş', 'it', 'məşhur', 'böyümək', 'dolaşmaq', 'getdikcə', 'başqa',
             'yaşamaq', 'ağ', 'istək', 'kənarda', 'cəhd', 'qardaş', 'çəkilmək', 'harada', 'oynamaq', 'icazə', 'qorxu',
             'iş', 'polis', 'yalnız', 'izah', 'fikir', 'sürətli', 'pəncərə', 'göstərmək', 'daş', 'yanğın', 'fərq',
             'yetər', 'çox', 'kimi', 'vəziyyət', 'məhəllə', 'mütləq', 'hissə', 'istehsal', 'bitdi', 'dayanmaq', 'Nazik',
             'qədər', 'ortaq', 'dərman', 'görüntü', 'ildən', 'dərs', 'nazir', 'qarşılıq', 'Xilas', 'nömrə', 'dəfə',
             'ediləcək', 'Qərb', 'danışmaq', 'hərhansı', 'kino', 'qəribə', 'hədəf', 'yatmaq', 'dost', 'yanmaq',
             'anlayış', 'kral', 'basmaq', 'kənar', 'nəzarət', 'çevirmək', 'din', 'güclü', 'hələ', 'plan', 'beyin',
             'elektrik', 'qadın', 'yuxarıda', 'ət', 'təmin', 'gileylənmək', 'xətt', 'uçmaq', 'üzv', 'dəri', 'ruh',
             'sevgili', 'yanaşma', 'dövr', 'baxış', 'Elm', 'Daha', 'ifadə', 'bədən', 'xatırlamaq', 'qəza',
             'hərtərəfli', 'dağ', 'yaxın', 'mənim', 'ciddi', 'həll', 'təsir', 'bələdiyyə', 'inkişaf', 'seçim',
             'ağlamaq', 'bağlı', 'anlayış', 'artırmaq', 'fəaliyyət', 'zərər', 'dərin', 'salon', 'növ', 'kəsilmək',
             'baxmaq', 'birdən', 'ehtiva', 'sayılmaq', 'toplamaq', 'aşmaq', 'bağırmaq', 'məsuliyyət', 'davranmaq',
             'məktub', 'soyuq', 'canlı', 'hərəkət', 'maşın', 'fayda', 'yaşlı', 'boş', 'Maraqlıdır', 'uyğun', 'icraçı',
             'gətirilmək', 'metrə', 'tutulmaq', 'keyfiyyət', 'bitki', 'dəyişmək', 'dərman', 'kredit', 'yaşamaq', 'uğurlu',
             'birbir', 'imkan', 'cəza', 'hərşey', 'yoxlamaq', 'top', 'ekspert', 'doldurmaq', 'kanal', 'məkan', 'yaraşmaq',
             'illik', 'Dolaşıq', 'yazılmaq', 'aid', 'barmaq', 'saymaq', 'atılmaq', 'Tapmaq', 'normal', 'hələ',
             'prinsip', 'qırmızı', 'rol', 'mahnı', 'İşçi', 'hazır', 'bənzəmək', 'birşey', 'müəllim', 'boy', 'günlük', 'siyasət',
             'cinayət', 'niyə', 'səhnə', 'sancmaq', 'adət', 'oturacaq', 'qorumaq', 'rəssam', 'üstünlük', 'uzanmaq', 'mərhələ',
             'əlavəetmək', 'Meşə', 'ayırmaq', 'sifariş', 'faiz', 'Ümumiyyətlə', 'hərzaman', 'hekayə', 'hüceyrə', 'orada', 'roman',
             'vergi', 'yandırmaq', 'qardaş', 'basın', 'dəstək', 'geyinmək', 'səhv', 'sərhəd', 'birlik', 'iş', 'görüşmək',
             'yarı', 'kifayətdir', 'fərdi', 'qaranlıq', 'avtobus', 'sənaye', 'körpə', 'vətəndaş', 'nazir', 'dəfə', 'millət',
             'reklam', 'yüksəlmək', 'ölçü', 'jurnal', 'inflyasiya', 'sosial', 'kimsə', 'keçmiş', 'xəstəxana', 'varlıq',
             'görüş', 'jurnalist', 'içəri', 'inam', 'ixtisas', 'yuxarıda', 'bitirmək', 'başverir', 'giriş', 'rahat',
             'ümumi', 'bərabər', 'dükan', 'gizli', 'oxşar', 'dəri', 'çevrilmək', 'mübarizə', 'problem', 'xidmət', 'müalicə',
             'yaşıl', 'nazirlik', 'zülm', 'reaksiya', 'cümlə', 'arzu', 'azadlıq', 'yenidən', 'şəxsiyyət', 'problem', 'üçüncü',
             'təyin', 'qiymətləndirmək', 'maraqlı', 'sürücü', 'süd', 'tutmaq', 'əşya', 'beynəlxalq', 'ərizəçi',
             'ağırlıq', 'milyard', 'sağlam', 'problem', 'Allah', 'münasibət', 'sosial', 'yayım', 'diqqətliolmaq', 'sondərəcə',
             'toplamaq', 'investisiya', 'işıq', 'müdaxilə', 'təhlükə', 'vaxt', 'dairə', 'fürsət', 'tutmaq', 'qarışdırmaq',
             'töhfə', 'hekayə', 'tamamilə', 'təyyarə', 'cavab', 'təbiət', 'evlənmək', 'burun', 'maraq', 'əlbəttə', 'işçi', 'Biznes',
             'qısaca', 'mağaza', 'medya', 'çünki', 'artırmaq', 'çıxarılsın', 'ictimai', 'sığorta', 'yaz', 'ürək', 'sənəd',
             'səy', 'hərgün', 'ifadəetmək', 'risk', 'qeydetmək', 'söz', 'demokratiya', 'duz', 'məscid', 'çay', 'aşağı',
             'ətrafında', 'tez', 'imkanlı', 'orqan', 'öldürmək', 'başqa', 'il', 'Qırmaq', 'maraqlanmaq', 'meyvə', 'dolanmaq',
             'şirin', 'ayaq', 'dəyişmək', 'qanun', 'külək', 'respublika', 'inkişaf', 'üslub', 'yeddi', 'azalmaq',
             'bağlamaq', 'telefon', 'Əlaqə', 'menecer', 'otel', 'nəşr', 'zövq', 'minmək', 'təhlükəsizlik', 'qanun',
             'etmək', 'müasir', 'oxucu', 'silah', 'xahiş', 'ulduz', 'sıxıcı', 'əsgər', 'sadə', 'çağırmaq', 'qaz',
             'tətbiq', 'istehsal', 'bəyannamə', 'yemək', 'dünən', 'görüşmək', 'təxminən', 'alışveriş', 'şüur', 'çərçivə',
             'lazım', 'mövcud', 'istehlakçı', 'uzatmaq', 'yönümlü', 'at', 'bağlanmaq', 'misal', 'təxminən', 'Sayt',
             'kömək', 'bacı', 'çiçək', 'hamısı', 'hörmət', 'haqq', 'istedad', 'kilo', 'paylaşmaq', 'çətin', 'başqa',
             'çay', 'xərc', 'müəyyən', 'zəngin', 'heçvaxt', 'söz', 'təşkilat', 'ticarət', 'düzəldi', 'boyun', 'qurğu',
             'balans', 'getdikcə', 'geri', 'çünki', 'qəhvə', 'kaş', 'məclis', 'başqa', 'göstərmək', 'ünvan', 'dəqiqləşdirilməlidir',
             'paşa', 'istilik', 'tamam', 'güvən', 'brend', 'yarpaq', 'fayda', 'yayılmaq', 'axmaq', 'çəkmək', 'düşünmək',
             'könül', 'yuxu', 'İlərləmək', 'şərab', 'yuxarıda', 'qızıl', 'təşkil', 'Satınalma', 'təqdim', 'təmiz',
             'vitamin', 'əlavə', 'gec', 'hərəkət', 'yumurta', 'ifrat', 'eyləm', 'istənilmək', 'kəsmək', 'böhran', 'vahid',
             'Kəs'
             ]


def kelime_sec():
    return random.choice(kelimeler)
